#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/franela/goblin"
  version = "74c9fe110d4bfd04c222a089a309e0a97e258534"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "a78ae492d53aad5a7a232d0d0462c14c400e3ee7"
